apiVersion: v1
kind: Service
metadata:
  name: crypto-dash-service
  labels:
    app: crypto-dash
spec:
  type: NodePort
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      nodePort: 30002
      protocol: TCP
  selector:
    app: crypto-dash