apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana-dash
spec:
  type: NodePort
  ports:
    - name: web
      port: 3000
      nodePort: 30001
      targetPort: 3000
  selector:
    app: grafana-dash