apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    app: influxdb
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 8086
      targetPort: 8086
    - name: rpc
      port: 8088
      targetPort: 8088
  selector:
    app: influxdb