apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: c-kafka
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka-internal-port
  selector:
    app: c-kafka