apiVersion: v1
kind: Service
metadata:
  name: kafka-public-svc
  labels:
    app: c-kafka
spec:
  type: ClusterIP
  ports:
    - port: 30092
      targetPort: 30092
      name: kafka-public-port
  selector:
    app: c-kafka